### ISSUE TITLE
Any chance of getting heightfields implemented on Newton?

### ISSUE THREAD

**Issue by manacoa** [CoppeliaRobotics/dynamicsPlugin#1]
As I mentioned in my V-REP posting

http://www.forum.coppeliarobotics.com/viewtopic.php?f=9&t=8003

heightfields don't appear to work with Newton. They are, however, available on the original engine, so I guess this is something that needs finishing on the plugin.

The admin on the forum mentioned a TODO in the file CollShapeDyn_newton.cpp

Thanks

Simon

**Comment by Coppelia** [comment]
Hi Simon,

we just pushed a fix. I'll try to make binaries available soon

Cheers

**Comment by SimonBirrell** [comment]
Wonderful! Thanks!! It's a great physics engine, so I think the effort is worth it.

For the binaries, are we talking days or weeks? (It's to figure out my strategy for delivering my latest paper!)

**Comment by Coppelia** [comment]
I replied to your forum post, the binaries can be found [there](http://www.forum.coppeliarobotics.com/viewtopic.php?f=9&t=8003&p=31135#p31135).

Cheers

**Comment by SimonBirrell** [comment]
You sir, are a gent!

Thanks so much.
